name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CI: true
  DEPLOY_TARGET: gh-pages
  NEXT_PUBLIC_BASE_PATH: /blog-nextjs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build # runs `next build`
      - run: npm run export # runs `next export`
      - run: touch ./out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
